import Head from 'next/head';
import Link from 'next/link';

export default function Terms() {
  return (
    <>
      <Head>
        <title>Terms of Service | Repurpose AI</title>
        <meta name="description" content="Terms of Service for Repurpose AI" />
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet" />
      </Head>

      <div style={styles.container}>
        <nav style={styles.nav}>
          <Link href="/" style={styles.navLogo}>
            REPURPOSE<span style={styles.logoAccent}>_</span>
          </Link>
        </nav>

        <main style={styles.main}>
          <h1 style={styles.title}>Terms of Service</h1>
          <p style={styles.updated}>Last updated: December 19, 2025</p>

          <section style={styles.section}>
            <h2 style={styles.heading}>1. Acceptance of Terms</h2>
            <p style={styles.text}>
              By accessing or using Repurpose AI ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>2. Description of Service</h2>
            <p style={styles.text}>
              Repurpose AI is a content transformation tool that converts articles and web content into social media posts for platforms including Twitter/X, LinkedIn, and Threads. The Service uses artificial intelligence to generate content based on URLs you provide.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>3. User Accounts</h2>
            <p style={styles.text}>
              You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities under your account. You must provide accurate information when creating your account.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>4. Acceptable Use</h2>
            <p style={styles.text}>You agree not to use the Service to:</p>
            <ul style={styles.list}>
              <li>Generate content that infringes on intellectual property rights</li>
              <li>Create misleading, deceptive, or fraudulent content</li>
              <li>Produce spam or unsolicited communications</li>
              <li>Generate content that is illegal, harmful, or violates platform terms of service</li>
              <li>Circumvent usage limits or abuse the Service</li>
              <li>Resell or redistribute the Service without permission</li>
            </ul>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>5. Content Ownership</h2>
            <p style={styles.text}>
              You retain ownership of any content you create using the Service. However, you are responsible for ensuring you have the right to repurpose the source content you submit. We do not claim ownership of your generated content.
            </p>
            <p style={styles.text}>
              You grant us a limited license to process the URLs and content you submit solely for the purpose of providing the Service.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>6. Subscription and Payments</h2>
            <p style={styles.text}>
              <strong>Free Tier:</strong> Includes 3 content generations per day at no cost.
            </p>
            <p style={styles.text}>
              <strong>Pro Subscription:</strong> $9/month for unlimited generations. Subscriptions are billed monthly and automatically renew until cancelled.
            </p>
            <p style={styles.text}>
              <strong>Cancellation:</strong> You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. No refunds are provided for partial months.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>7. Service Availability</h2>
            <p style={styles.text}>
              We strive to maintain high availability but do not guarantee uninterrupted service. We may modify, suspend, or discontinue the Service at any time with reasonable notice. We are not liable for any downtime or service interruptions.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>8. AI-Generated Content Disclaimer</h2>
            <p style={styles.text}>
              Content generated by the Service is created by artificial intelligence and may contain errors, inaccuracies, or inappropriate content. You are responsible for reviewing and editing all generated content before publishing. We do not guarantee the accuracy, quality, or appropriateness of generated content.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>9. Limitation of Liability</h2>
            <p style={styles.text}>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, REPURPOSE AI SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM YOUR USE OF THE SERVICE.
            </p>
            <p style={styles.text}>
              Our total liability for any claims arising from your use of the Service shall not exceed the amount you paid us in the 12 months preceding the claim.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>10. Indemnification</h2>
            <p style={styles.text}>
              You agree to indemnify and hold harmless Repurpose AI from any claims, damages, or expenses arising from your use of the Service, your violation of these Terms, or your violation of any third-party rights.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>11. Modifications to Terms</h2>
            <p style={styles.text}>
              We reserve the right to modify these Terms at any time. We will notify users of significant changes via email or through the Service. Continued use of the Service after changes constitutes acceptance of the modified Terms.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>12. Termination</h2>
            <p style={styles.text}>
              We may terminate or suspend your account at any time for violation of these Terms or for any other reason at our discretion. Upon termination, your right to use the Service ceases immediately.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>13. Governing Law</h2>
            <p style={styles.text}>
              These Terms are governed by the laws of Ontario, Canada. Any disputes shall be resolved in the courts of Ontario.
            </p>
          </section>

          <section style={styles.section}>
            <h2 style={styles.heading}>14. Contact</h2>
            <p style={styles.text}>
              For questions about these Terms, contact us at legal@repurposeai.app
            </p>
          </section>
        </main>

        <footer style={styles.footer}>
          <Link href="/" style={styles.footerLink}>← Back to Home</Link>
        </footer>
      </div>

      <style jsx global>{`
        * { box-sizing: border-box; margin: 0; padding: 0; }
        body { background: #0a0a0a; color: #e5e5e5; font-family: 'Inter', -apple-system, sans-serif; }
        li { color: #888; margin-bottom: 8px; line-height: 1.6; }
      `}</style>
    </>
  );
}

const styles = {
  container: { minHeight: '100vh', background: '#0a0a0a' },
  nav: { padding: '20px 40px', borderBottom: '1px solid #151515' },
  navLogo: { fontSize: '20px', fontWeight: 800, color: '#fff', textDecoration: 'none', fontFamily: "'JetBrains Mono', monospace" },
  logoAccent: { color: '#00ff88' },
  main: { maxWidth: '700px', margin: '0 auto', padding: '60px 24px' },
  title: { fontSize: '36px', fontWeight: 700, color: '#fff', marginBottom: '8px' },
  updated: { fontSize: '14px', color: '#555', marginBottom: '48px' },
  section: { marginBottom: '40px' },
  heading: { fontSize: '20px', fontWeight: 600, color: '#fff', marginBottom: '16px' },
  text: { fontSize: '15px', color: '#888', lineHeight: 1.7, marginBottom: '12px' },
  list: { paddingLeft: '24px', marginTop: '12px' },
  footer: { padding: '40px', borderTop: '1px solid #151515', textAlign: 'center' },
  footerLink: { fontSize: '14px', color: '#555', textDecoration: 'none' },
};
